E2Helper.Descriptions["runOnWeaponSwitch"] = "If set to 1, the chip will be executed when the player switches weapons."
E2Helper.Descriptions["weaponSwitchClk"] = "Returns 1 if the player has switched weapons."
E2Helper.Descriptions["lastWeaponSwitchPlayer"] = "Returns the player that switched weapons."
E2Helper.Descriptions["lastWeaponSwitchOld"] = "Returns the weapon the player switched from."
E2Helper.Descriptions["lastWeaponSwitchNext"] = "Returns the weapon the player switched to."
E2Helper.Descriptions["runOnWeaponEquip"] = "Is set to 1, E2 will run when a player equips a weapon."
E2Helper.Descriptions["weaponEquipClk"] = "Returns 1 if the E2 is run because of a weapon equip."
E2Helper.Descriptions["lastWeaponEquip"] = "Returns the last equipped weapon."

E2Helper.Descriptions["plyGive"] = "Give the player a weapon."
E2Helper.Descriptions["plyGiveWeapon"] = "Give the player a weapon."
E2Helper.Descriptions["plyGiveAmmo"] = "Gives ammo to a player."
E2Helper.Descriptions["plySetAmmo"] = "Sets the amount of of the specified ammo for the player."
E2Helper.Descriptions["plySelectWeapon"] = "Sets the player active weapon."
E2Helper.Descriptions["plyDropWeapon"] = "Forces the player to drop the specified weapon."
E2Helper.Descriptions["plyStripWeapon"] = "Removes the specified weapon from a certain player "
E2Helper.Descriptions["plyStripWeapons"] = "Removes all weapons from a certain player "
E2Helper.Descriptions["plyStripAmmo"] = "Removes all ammo from the player."
E2Helper.Descriptions["plySetClip1"] = "Lets you change the number of bullets in the given weapons primary clip."
E2Helper.Descriptions["plySetClip2"] = "Lets you change the number of bullets in the given weapons secondary clip."

E2Helper.Descriptions["getWeapon"] = "Returns the weapon entity whit the class."
E2Helper.Descriptions["getWeapons"] = "Returns a table of the player's weapons."
E2Helper.Descriptions["hasWeapon"] = "Returns if the player has the specified weapon."